In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
dataset = pd.read_csv('/content/datamentqh.csv', sep=';')

In [12]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [8]:
print(x)

[]


In [13]:
print (y)

[1250  980 1450  820  760 1100  870  690  540]


In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0,1])
    ],
    remainder='passthrough'
)

x = ct.fit_transform(x).toarray()

In [15]:
print (x)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [16]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=1
)

In [17]:
print (x_test)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
print (x_train)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [19]:
print (y_test)

[ 540 1450]


In [20]:
print (y_train)

[ 870  690  980 1250  760  820 1100]


In [21]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [22]:
print(x_train)

[[ 2.44948974  0.          0.         -0.40824829 -0.40824829 -0.40824829
  -0.40824829 -0.40824829 -0.40824829 -0.40824829  0.         -0.40824829
  -0.40824829 -0.40824829 -0.40824829 -0.40824829  0.          2.44948974]
 [-0.40824829  0.          0.          2.44948974 -0.40824829 -0.40824829
  -0.40824829 -0.40824829 -0.40824829 -0.40824829  0.         -0.40824829
  -0.40824829  2.44948974 -0.40824829 -0.40824829  0.         -0.40824829]
 [-0.40824829  0.          0.         -0.40824829 -0.40824829 -0.40824829
   2.44948974 -0.40824829 -0.40824829  2.44948974  0.         -0.40824829
  -0.40824829 -0.40824829 -0.40824829 -0.40824829  0.         -0.40824829]
 [-0.40824829  0.          0.         -0.40824829 -0.40824829  2.44948974
  -0.40824829 -0.40824829 -0.40824829 -0.40824829  0.         -0.40824829
   2.44948974 -0.40824829 -0.40824829 -0.40824829  0.         -0.40824829]
 [-0.40824829  0.          0.         -0.40824829  2.44948974 -0.40824829
  -0.40824829 -0.40824829 -0.40824

In [24]:
print (x_test)

[[-0.40824829  1.          0.         -0.40824829 -0.40824829 -0.40824829
  -0.40824829 -0.40824829 -0.40824829 -0.40824829  0.         -0.40824829
  -0.40824829 -0.40824829 -0.40824829 -0.40824829  1.         -0.40824829]
 [-0.40824829  0.          1.         -0.40824829 -0.40824829 -0.40824829
  -0.40824829 -0.40824829 -0.40824829 -0.40824829  1.         -0.40824829
  -0.40824829 -0.40824829 -0.40824829 -0.40824829  0.         -0.40824829]]


In [25]:
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Nama game   9 non-null      object
 1   Genre       9 non-null      object
 2   jumlah      9 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 348.0+ bytes
None


In [26]:
print(dataset.head())

       Nama game            Genre  jumlah
0  Mobile legend             MOBA    1250
1           PUBG    Battle Royale     980
2       Free Fire  Battle rRoyale    1450
3        Valorant             FPS     820
4        Minecref         Sandbox     760
